<a href="https://colab.research.google.com/github/Fernandotambun/Tugas3-Datamining/blob/main/Tugas_2_Data_Mining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset=pd.read_csv('dataset_customerini.csv')
x = dataset.iloc[:, :-2].values
y = dataset.iloc[:, -1].values
z = dataset.iloc[:, -2].values

In [ ]:
print(x)

[['South' 44.0 64000.0]
 ['West' 33.0 136000.0]
 ['West' nan nan]
 ...
 ['West' 31.0 24000.0]
 ['West' 42.0 81000.0]
 ['South' 24.0 nan]]


In [ ]:
print(y)

['Female' 'Female' 'Male' 'Male' 'Female' 'Male' 'Male' 'Female' 'Female'
 'Female' 'Male' 'Male' 'Male' 'Male' 'Male' 'Female' 'Female' 'Male'
 'Female' 'Female' 'Male' 'Female' 'Male' 'Female' 'Female' 'Male' 'Male'
 'Female' 'Male' 'Male' 'Male' 'Female' 'Male' 'Female' 'Female' 'Female'
 'Female' 'Female' 'Male' 'Male' 'Female' 'Male' 'Female' 'Female' 'Male'
 'Female' 'Female' 'Female' 'Male' 'Male' 'Female' 'Female' 'Female'
 'Female' 'Female' 'Male' 'Male' 'Female' 'Male' 'Male' 'Male' 'Male'
 'Female' 'Male' 'Female' 'Female' 'Male' 'Female' 'Female' 'Male'
 'Female' 'Male' 'Female' 'Male' 'Female' 'Female' 'Female' 'Female'
 'Male' 'Male' 'Male' 'Female' 'Female' 'Male' 'Male' 'Female' 'Female'
 'Female' 'Male' 'Female' 'Female' 'Male' 'Male' 'Male' 'Male' 'Female'
 'Female' 'Male' 'Male' 'Male' 'Female' 'Male' 'Female' 'Male' 'Male'
 'Male' 'Female' 'Male' 'Female' 'Female' 'Male' 'Male' 'Male' 'Female'
 'Male' 'Male' 'Female' 'Male' 'Female' 'Female' 'Male' 'Female' 'Female'

In [ ]:
print(z)

['married' 'married' 'married' 'single' 'married' 'single' 'married'
 'single' 'married' 'married' 'single' 'single' 'married' 'married'
 'single' 'married' 'single' 'single' 'single' 'married' 'single'
 'married' 'single' 'married' 'married' 'single' 'single' 'married'
 'married' 'married' 'married' 'married' 'married' 'married' 'married'
 'married' 'single' 'married' 'married' 'single' 'single' 'single'
 'married' 'married' 'married' 'married' 'married' 'married' 'married'
 'single' 'married' 'married' 'single' 'married' 'single' 'married'
 'single' 'married' 'single' 'married' 'married' 'married' 'single'
 'married' 'single' 'married' 'married' 'married' 'single' 'single'
 'married' 'single' 'single' 'single' 'married' 'single' 'married'
 'single' 'single' 'single' 'married' 'single' 'married' 'single'
 'married' 'married' 'single' 'married' 'single' 'married' 'married'
 'single' 'married' 'single' 'married' 'single' 'married' 'married'
 'married' 'single' 'single' 'married' 'single

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:,1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[[0.0 1.0 0.0 44.0 64000.0]
 [0.0 0.0 1.0 33.0 136000.0]
 [0.0 0.0 1.0 41.450934579439256 76932.12669683258]
 ...
 [0.0 0.0 1.0 31.0 24000.0]
 [0.0 0.0 1.0 42.0 81000.0]
 [0.0 1.0 0.0 24.0 76932.12669683258]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 1.0 0.0 44.0 64000.0]
 [1.0 0.0 0.0 1.0 33.0 136000.0]
 [1.0 0.0 0.0 1.0 41.450934579439256 76932.12669683258]
 ...
 [1.0 0.0 0.0 1.0 31.0 24000.0]
 [1.0 0.0 0.0 1.0 42.0 81000.0]
 [1.0 0.0 1.0 0.0 24.0 76932.12669683258]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
z = le.fit_transform(z)

In [ ]:
print(y)

[0 0 1 1 0 1 1 0 0 0 1 1 1 1 1 0 0 1 0 0 1 0 1 0 0 1 1 0 1 1 1 0 1 0 0 0 0
 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 1 0 1 1 1 1 0 1 0 0 1 0 0 1 0 1 0 1
 0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 1 0 1 0 1 1 1 0 1 0 0 1
 1 1 0 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 1 1 0 1
 1 0 1 1 1 0 0 1 0 0 1 1 1 1 0 1 1 0 0 1 0 0 0 1 1 1 1 0 1 0 1 1 0 0 0 0 0
 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 1 1
 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 0 1 0 1 1 0 0
 0 1 1 1 1 1 1 0 0 0 1 1 0 0 0 1 0 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 0 1 1 0 0
 0 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 0
 1 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 1
 0 0 1 0 1 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 0 0 0 1 1 0 1 1 1 1 0 0 1 1 1 1 1
 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0
 0 1 1 0 0 0 0 0 0 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 1 1 0 1 1
 0 1 1 0 0 0 1 0 0 0 1 0 

In [ ]:
print(z)

[0 0 0 1 0 1 0 1 0 0 1 1 0 0 1 0 1 1 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1
 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 1 0 1 1 1
 0 1 0 1 1 1 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 1 1 1 0 0
 0 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 1 1 0 0
 0 1 0 1 1 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 0 1 1 0 1 0 0 1
 1 0 0 0 0 0 1 1 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 0 0 1 1 1
 1 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 0 1 0 1 0 1 1 1 1 0 0 1 0 0 1 1 0 1 0 1
 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1
 1 1 1 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1
 1 0 1 0 0 1 0 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 1 0
 0 0 1 1 1 0 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 1 0 1 0 0 0
 1 1 1 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 1 1 0 1 0 1
 0 1 0 1 0 0 0 0 1 1 1 1 0 1 1 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0
 0 0 1 1 1 0 1 0 1 1 1 1 

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test, z_train, z_test = train_test_split(x, y, z, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 1.0 0.0 0.0 41.450934579439256 72000.0]
 [1.0 0.0 1.0 0.0 55.0 26000.0]
 [1.0 0.0 1.0 0.0 41.450934579439256 30000.0]
 ...
 [1.0 0.0 1.0 0.0 43.0 146000.0]
 [1.0 0.0 1.0 0.0 57.0 37000.0]
 [0.0 1.0 0.0 0.0 57.0 186000.0]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 1.0 50.0 102000.0]
 [1.0 0.0 0.0 1.0 41.450934579439256 20000.0]
 [1.0 0.0 1.0 0.0 64.0 9000.0]
 [1.0 0.0 0.0 1.0 41.450934579439256 45000.0]
 [0.0 1.0 0.0 0.0 54.0 57000.0]
 [1.0 0.0 1.0 0.0 61.0 76000.0]
 [0.0 1.0 0.0 0.0 43.0 38000.0]
 [1.0 0.0 1.0 0.0 65.0 9000.0]
 [1.0 0.0 0.0 1.0 47.0 37000.0]
 [1.0 0.0 1.0 0.0 42.0 65000.0]
 [0.0 1.0 0.0 0.0 31.0 42000.0]
 [1.0 0.0 0.0 1.0 47.0 63000.0]
 [1.0 0.0 0.0 1.0 23.0 19000.0]
 [1.0 0.0 0.0 1.0 36.0 76932.12669683258]
 [0.0 1.0 0.0 0.0 21.0 19000.0]
 [1.0 0.0 0.0 1.0 26.0 32000.0]
 [1.0 0.0 0.0 1.0 41.450934579439256 36000.0]
 [1.0 0.0 0.0 1.0 26.0 25000.0]
 [0.0 1.0 0.0 0.0 53.0 76932.12669683258]
 [1.0 0.0 1.0 0.0 51.0 41000.0]
 [1.0 0.0 1.0 0.0 27.0 46000.0]
 [0.0 1.0 0.0 0.0 41.450934579439256 86000.0]
 [0.0 1.0 0.0 0.0 39.0 122000.0]
 [1.0 0.0 0.0 1.0 31.0 59000.0]
 [1.0 0.0 0.0 1.0 36.0 67000.0]
 [1.0 0.0 0.0 1.0 41.450934579439256 181000.0]
 [1.0 0.0 1.0 0.0 46.0 163000.0]
 [1.0 0.0 0.0 1.0 28.0 76932.12669683258]
 [

In [ ]:
print(y_train)

[1 0 1 1 1 1 0 0 1 0 1 1 1 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0
 1 1 0 0 0 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0 0 0 1 1 0
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 1 1 1 1 0 1 0 1 1 1 0 0 1 1 1 1
 0 1 0 1 1 0 1 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0
 1 0 0 0 1 1 0 1 1 0 0 1 0 0 1 0 0 1 0 1 1 1 0 1 1 0 1 0 0 0 0 0 1 0 1 0 1
 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1
 0 0 0 0 0 1 0 1 0 1 1 1 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0
 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0
 1 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0 1 0 1 1 1 0 1 1 1 0 1 0 1 0 1 0 1 0 0 0 0
 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 0 0 1 1 1 0 0 0 0 1 1 1 0
 0 1 1 0 0 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 1 0 1 1 0 1 0 0]


In [ ]:
print(y_test)

[1 1 1 1 1 0 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 0 0 1 1 0
 1 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 1 1 1 1 1 1 0 0 0 1 1 1
 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 1]


In [ ]:
print(z_train)

[1 1 1 0 1 0 0 1 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1 0 0 0 1
 1 1 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 1 0 0 0 1 1 0 0 0 1 1 0 0 1 0 0 0 1 1 0
 0 0 1 1 1 1 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1
 0 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 1 1 0
 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 0 1 0 1 1 1 1 1 1 0 0 0 0
 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 1 0
 1 0 0 1 1 0 0 1 0 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 1 0 0 1 0 1 0 1 1 0 0 0 1
 0 0 0 1 0 1 1 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 1 0 0 0
 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 0 0 0 1 1 0 0 0 1 1 1 1 0 1
 0 0 0 1 1 0 0 1 1 1 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 0 1 1
 0 1 1 1 0 1 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 1 0]


In [ ]:
print(z_test)

[0 0 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 1 0 0
 0 1 0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 1 0 1 1 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 1
 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 0 0 1 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 1.0 0.0 -0.6558258357839528 0.02422830889068139
  -0.05204937831694189]
 [1.0 0.0 1.0 -0.6558258357839528 1.219602966961921 -0.6580062343881287]
 [1.0 0.0 1.0 -0.6558258357839528 0.02422830889068139 -0.6053143338601994]
 ...
 [1.0 0.0 1.0 -0.6558258357839528 0.16089556157239038 0.9227507814497499]
 [1.0 0.0 1.0 -0.6558258357839528 1.3960542011935093 -0.5131035079363232]
 [0.0 1.0 0.0 -0.6558258357839528 1.3960542011935093 1.449669786729043]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 0.999999999999997 49.99999999999996 102000.00000000006]
 [1.0 0.0 0.0 0.999999999999997 41.45093457943922 20000.00000000001]
 [1.0 0.0 1.0 -1.3912569230891646e-16 63.99999999999994 9000.000000000005]
 [1.0 0.0 0.0 0.999999999999997 41.45093457943922 45000.00000000002]
 [0.0 1.0 0.0 -1.3912569230891646e-16 53.99999999999995 57000.00000000003]
 [1.0 0.0 1.0 -1.3912569230891646e-16 60.99999999999994 76000.00000000004]
 [0.0 1.0 0.0 -1.3912569230891646e-16 42.999999999999964
  38000.00000000002]
 [1.0 0.0 1.0 -1.3912569230891646e-16 64.99999999999994 9000.000000000005]
 [1.0 0.0 0.0 0.999999999999997 46.99999999999996 37000.00000000002]
 [1.0 0.0 1.0 -1.3912569230891646e-16 41.999999999999964
  65000.00000000004]
 [0.0 1.0 0.0 -1.3912569230891646e-16 30.999999999999975
  42000.00000000002]
 [1.0 0.0 0.0 0.999999999999997 46.99999999999996 63000.00000000004]
 [1.0 0.0 0.0 0.999999999999997 22.999999999999982 19000.00000000001]
 [1.0 0.0 0.0 0.999999999999997 35.99999999999997 